### PR TITLE
Fix using bare raise_error matcher

### PR DESCRIPTION
**Pull request by takiy33**
I fix some warnings on rspec

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
This is great, thanks!  If you look at the Travis build (click on "Details" for the failing check above) you'll see that jRuby isn't passing because there's one case where you're specifying `ArgumentError` but it's giving something else.  Could you try changing `lib/neo4j-embedded/embedded_node.rb` on line 171 to this:

```ruby
fail "Expected to only find one relationship from node #{neo_id} matching" if iter.has_next
```

I think that was copy/pasted from `CypherNode` and so it wasn't quite right

**Comment by cheerfulstoic** [comment]
This is great, thanks!  If you look at the Travis build (click on "Details" for the failing check above) you'll see that jRuby isn't passing because there's one case where you're specifying `ArgumentError` but it's giving something else.  Could you try changing `lib/neo4j-embedded/embedded_node.rb` on line 171 to this:

```ruby
fail "Expected to only find one relationship from node #{neo_id} matching" if iter.has_next
```

I think that was copy/pasted from `CypherNode` and so it wasn't quite right

**Comment by takiy33** [comment]
@cheerfulstoic I am sorry for late reply. 
I will try it.

**Comment by takiy33** [comment]
I modified this PR for passing test.
And, I was change to explicitly raising ArgumentError.

**Comment by cheerfulstoic** [comment]
Awesome, thanks!  Looks like it's failing for jruby-1.7.20 because of a Gemfile issue, but I should be able to fix that pretty quickly after mereg

**Comment by takiy33** [comment]
Thank you for merging :star:

**Comment by cheerfulstoic** [comment]
Thanks for contributing! :metal:

**Pull request merged**
