### PR TITLE
Remove unused test

### PR DESCRIPTION
**Pull request by takiy33**

### CODE REVIEW

**Comment by takiy33** [comment]
Somehow the Coveralls fails.

**Comment by cheerfulstoic** [comment]
IMO coveralls can be kind of flakey in this regard ;)

That's for catching this!

**Comment by cheerfulstoic** [comment]
Errr, "thanks" also for catching this ;)

**Comment by takiy33** [comment]
I am sorry for removing my comment.
Below is removed comment.

> Somehow Coveralls is failed.

**Pull request merged**
