### PR TITLE
Support ActiveRecord style syntax ...

### PR DESCRIPTION
**Pull request by cheerfulstoic**
...of specifying a String and a value/set of params in `where` calls

@subvertallchris Waddaya think?  To address #675

The only problem that I see is if there are question marks in the query strings, but people shouldn't be interpolating strings into `where` calls anyway....

### CODE REVIEW

**Comment by subvertallchris** [comment]
Looks really cool! Very happy to see this. I think `question_mark_param` should append a counter to it or do something to make it unique within a query. If someone has multiple `where` methods in a chain, reusing that same param will cause problems.

**Comment by cheerfulstoic** [comment]
Good point!  On it...

**Comment by cheerfulstoic** [comment]
Off to bed.  Will merge tomorrow if all looks good

**Comment by subvertallchris** [comment]
Looks good to me!

**Comment by cheerfulstoic** [comment]
Thanks ;p

**Pull request merged**
