### PR TITLE
Check emptiness of index schema response body to protect from empty string

### PR DESCRIPTION
**Pull request by kylegrantlucas**
Fixes

I experienced an issue while running a neo4j migration on GrapheneDB. My index schema response.body was returning an empty string rather than a nil body or empty array.

Stack Trace: 

```
NoMethodError: undefined method `map' for "":String
Did you mean?  tap
/app/vendor/bundle/ruby/2.3.0/gems/neo4j-core-7.0.3/lib/neo4j/core/cypher_session/adaptors/http.rb:48:in `indexes'
/app/vendor/bundle/ruby/2.3.0/gems/neo4j-core-7.0.3/lib/neo4j/core/cypher_session.rb:36:in `block (2 levels) in <class:CypherSession>'
/app/vendor/bundle/ruby/2.3.0/gems/neo4j-core-7.0.3/lib/neo4j/core/label.rb:64:in `indexes'
/app/vendor/bundle/ruby/2.3.0/gems/neo4j-core-7.0.3/lib/neo4j/core/label.rb:96:in `index?'
/app/vendor/bundle/ruby/2.3.0/gems/neo4j-8.0.5/lib/neo4j/migrations/helpers/schema.rb:20:in `add_index'
```

This pull introduces/changes:

This fix protects that case by checking for the response.body and then checking it's emptiness (.empty? works on both Strings and Arrays).

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Thanks @kylegrantlucas !

What version of `neo4j-core` are you using?  I think I made a fix for this in 7.0.1 ([this commit](https://github.com/neo4jrb/neo4j-core/commit/b9976e4fa20c430d62d982bff536f382a1aa080c))

I unfortunately compounded the issue by not merging those changes to `master` (which I've now done)

**Comment by kylegrantlucas** [comment]
It seems i'm on 7.0.3.

```sh
$ grep neo4j Gemfile.lock
    neo4j (8.0.5)
      neo4j-core (>= 7.0.0)
    neo4j-core (7.0.3)
      neo4j-rake_tasks (>= 0.3.0)
    neo4j-rake_tasks (0.7.10)
```

However reviewing your attached commit, i'm not sure it would help in this case. 

It _seems_ like my ```response.body``` is returning ```""``` which would pass the ```return if !response_body.is_a?(Hash) || !response_body.key?(:errors)``` check and continue execution. Leading to the ```NoMethodError: undefined method `map' for "":String``` I saw above. 

Example of it returning true from the ```return if !response_body.is_a?(Hash) || !response_body.key?(:errors)``` check:

```
irb(main):001:0> response_body = ""
=> ""
irb(main):002:0> !response_body.is_a?(Hash) || !response_body.key?(:errors)
=> true
```

Also, I fixed the merge conflict from the ```master``` update.

**Comment by cheerfulstoic** [comment]
I see, good to know, thanks!  Two more questions:

 * Which version of Neo4j are you using?  I'm wondering if maybe this was a behavior change in Neo4j
 * Can you tell if the same thing happens with constraints?

**Comment by kylegrantlucas** [comment]
Seems to be a deeper issue here actually, when hit directly the Graphene instance returns the proper index schema structure. Going to investigate why it returns blank when it gets run from here.

Will close this and open a new PR when I know more.

**Pull request closed without merging**
