### PR TITLE
Pretty cypher

### PR DESCRIPTION
**Pull request by cheerfulstoic**
This allows for pretty Cypher queries.  It started with newlines but then I had to colorize the clauses too ;)  The default color for the clauses is cyan, but there are some specific colors for specific clauses so that they can be seen at a glance:

 * `CREATE`s are green
 * `MERGE`s are magenta
 * `DELETE`s are red
 * `SET (ON CREATE|ON MATCH)` are all yellow

I got the color idea from here: https://github.com/rails/rails/pull/20607

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
You can either call `Query#print_cypher` or `Query#to_cypher` with `pretty: true` to get this, by the way

**Comment by cheerfulstoic** [comment]
I still need to figure out how to make this a configuration option in the default logs.  The `Config` module is in `neo4j`, not `neo4j-core`, right?

**Comment by subvertallchris** [comment]
That's right. You could use an ENV here and `neo4j` can use CONFIG?

**Comment by cheerfulstoic** [comment]
It's worth a look, thanks ;)

I was also just thinking that it might be nice to, at some point, have a method which generates cypher which can be copy/pasted to the Neo4j console without needing to copy/paste the params individually as well.  We'd probably want to name the method appropriately so that it's clear that it's not for anything else

**Comment by itsmeduncan** [comment]
For anyone else that lands here and is using `neo4j-core` with a Rails app, you can just add the snippet below right after you setup the `Neo4j::Session`.

```ruby
Neo4j::Server::CypherSession.log_with do |message|
  Rails.logger.debug message
end
```

**Pull request merged**
