### PR TITLE
Implement Bolt Routing protocol (closes #322).

### LINKED ISSUE #322: Request for comments/thoughts/advice on implementing Bolt Routing.
👋 Hey folks! I recently migrated my Neo4j architecture to a Causal Cluster, and I've spent the past few days working on enhancing `neo4j-core` to support the Bolt Routing protocol---which is just Bolt with a little service discovery, er, bolted on---so that my application will be compatible. The highly 🚧 work-in-progress 🚧 Core branch lives [here](https://github.com/ignota/neo4j-core/tree/bolt-routing), with a corresponding wrapper branch [here](https://github.com/ignota/neo4j/tree/bolt-routing). It's something that I'll be happy to yield back to the community when it's ready, but I'm stuck on part of the load balancing logic and I was hoping folks with deeper insight into the overall architecture of the gem might have some thoughts or insights to share.

Currently, the adapter checks a connection out from a pool at the start of every transaction; the transaction hangs on to the connection for its duration, since each transaction has to start and end at the same database instance, then releases it back to the pool. The service discovery logic to disambiguate read-type connections from write-type connections is in place, and works fine. The rub is that when a transaction starts, we issue the Cypher `BEGIN` statement before we know what the meat of the transaction will look like---we don't know, at that point, whether the transaction will contain exclusively read statements or whether it will include write statements (which must pass through the cluster leader).

The JavaScript adapter library drives this problem down to the consumer---it assumes all queries are write queries and should pass through the leader unless the application specifically requests a read-only transaction. I don't think that'll work here, though.

What I would love to be able to do is have the complete battery of queries available before firing them off, so that I could check for whether it was safe to send them to a read instance or whether they needed to go through a write instance. But I can't see a way to make this work in the current architecture of the gem.

If any of the maintainers, or anyone with deeper insight into the gem's inner workings, has any thoughts, I'd be only too glad to hear them. Thanks in advance!

### PR DESCRIPTION
**Pull request by phyllisstein**
Fixes #322.

This pull introduces/changes:
* **Support for `bolt+routing`.** The `bolt+routing` protocol is necessary to connect to Neo4j Enterprise Causal Clusters. This PR adds support for its load-balancing and service discovery features, which are mostly... er... bolted onto the core Bolt protocol.

Caveats:
* **Tests needed.** It's in desperate need of some unit tests, but we've been using it in production at <https://ignota.com/> quite happily for a little over a week now.
* **Rubocop cleanup needed.** Shouldn't be too taxing.
* **Design up for grabs!** There are divergences with patterns used elsewhere in the gem, some intentional and some not-so-; this is my first time really digging deeply into its architecture, so I'm happy to entertain conversations about whether a better design could be arrived at.

Grateful as always for your thoughts and comments! Glad to be able to give something back to a project that's been invaluable to me these past few months. 💖

P.S.: Let me know if I can help set up a dev environment with Neo4j EE! Don't want you to have to go into it sight unseen.

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Hey!  Sorry, I'm not currently maintaining the gem but it's awesome that somebody worked on this!

Some former colleagues of mine were potentially going to be working on this, so I would like to give them a heads up:

@leviwilson

@StephenTurley

@walterg2

**Comment by StephenTurley** [comment]
Glad to see this being worked on too. Thank you! I recall the BOLT implementation having some performance issues compared to HTTP. Has that changed at all?

**Comment by cheerfulstoic** [comment]
I believe when I was last testing them they were comparable, but then I also implemented some improvements to the performance.  I don't remember the results, but I think it was something like a 5-15% improvement from before.  Those changes are on `master` of `neo4j-core`.  The biggest change didn't actually have anything to do with the Bolt protocol but had to do with the fact that logging string was always being generated (regardless of if the log level was set to log or not).  So the improvement should mainly be on production where you don't generally log the queries.

**Comment by phyllisstein** [comment]
@cheerfulstoic Thanks for pinging the right people! Sorry to hear you've stepped away from the gem, but good luck with whatever comes next.

@StephenTurley I've heard the same thing about performance issues, but unfortunately this changeset wouldn't touch them---it's still using the same Bolt protocol under the hood, it just adds the service discovery features from Bolt Routing onto the top.

**Comment by klobuczek** [comment]
@phyllisstein I just had literally a 5 minutes look through the PR so please excuse me if I missed some obvious details. Is the goal of the driver to provide load balancing for read-only databases?
One of the important features of bolt+routing is ensuring that one can read their own writes which is solved with bookmarks and which would need changes in the neo4j gem, its API and all the way to client code.

**Comment by joshjordan** [comment]
@phyllisstein have you continued to use this in production?

@klobuczek do you see any obvious issues? It seems that without the service discovery in this PR, we are left to find our own workarounds for dynamically discovering the elected leader in causual clusters, no? In other words, is this PR strictly an improvement despite not implementing bookmarks?

**Comment by phyllisstein** [comment]
Hey! Forgive me for neglecting this PR (and @klobuczek's very thoughtful and generous feedback in #322). I have indeed been using this code in production since I first submitted it. That said, I use the word "production" _extremely_ loosely in this context: the application I'm running sees very little traffic, so it's not impossible there are bugs lurking.

Reviewing the branch as it stands, I'd flag two areas of especial concern. The first is that the heuristics for creating and destroying sessions feel a little shady (there's [this](https://github.com/neo4jrb/neo4j-core/pull/323/files#diff-edc2af43a3209b4f5021eae4447d9618R53), e.g., and [all'a this](https://github.com/neo4jrb/neo4j-core/pull/323/files#diff-77d98b33168c09465e11586d4b0c2b8c)). If session handling is broken, your app might hang on to more open connections than it needs, hogging server memory and preventing Neo4j from gracefully accepting new connections. The second is that I plum quit before implementing [causal chaining](https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-causal-chaining). This has already introduced one or two bugs into my own app, especially with background jobs. In cases (like file uploads) where the asynchronous code runs soon after graph CRUD code, it's not impossible (indeed, not uncommon) for the job's environment to connect to a read replica that hasn't received the replicated transaction yet.

The first issue, sadly, is a bit of a `¯\_(ツ)_/¯` at this point, but I'll try to find some time to put some thought into the second this weekend. If you wind up experimenting with this branch, I'd be curious to know how it goes! And if you have any questions about your specific use case, I'd be happy to talk through them [over e-mail](mailto:daniel@daniel.sh).

**Comment by klobuczek** [comment]
@phyllisstein would you be interested in contributing or at least reviewing https://github.com/neo4jrb/neo4j-ruby-driver? It is meant to be a fully compliant neo4j driver on which are going to base the neo4j/neo4j-core gem. So unfortunately this PR will not make it to master anymore, but your experience would be invaluable in building the new solution on top of the driver.

**Comment by phyllisstein** [comment]
I've glanced at the driver code once or twice. It definitely looks impressive, and I'm glad to see that it's going to obviate this (imperfect, buggy) work. I've been looking at migrating my app to another stack, but kinda reluctantly. I'd love to learn more about where the Ruby driver code stands, what the delta is between its current state and getting it integrated with the OGM, and whether there's anything I can do to contribute.

Do you have a Slack set up or something? If not, my e-mail's in my profile, and I'd love to talk more.

**Comment by klobuczek** [comment]
Hi @phyllisstein we are all here: https://gitter.im/neo4jrb/neo4j#

**Pull request closed without merging**
