### PR TITLE
Use Typhoeus to help forked/threaded users

### LINKED ISSUE #241: Make Neo4j::Session.current thread-safe
I think that this would be pretty easy.  See: http://stackoverflow.com/questions/34233349/reconnect-neo4jrb-connections-after-puma-fork-with-preload-app/34281962#34281962

### PR DESCRIPTION
**Pull request by brucek**
Fixes #241.

This pull introduces/changes:
 * Using Typhoeus gem for http connections
 * Removed net-http-persistent

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

**Comment by brucek** [comment]
Not sure if you guys want to do this, but I get *much* better stability in my resque-pool multi-worker application using Typhoeus.  See my comments in https://github.com/drbrain/net-http-persistent/issues/37

**Comment by brucek** [comment]
Also I'm using this on the 6.1.x branch so I can only give data from there, but I ported it over to 7.0.x and it looks to be working.

**Comment by subvertallchris** [comment]
I seem to remember benchmarking the two adapters and finding
NetHttpPersistent much faster when using SSL. We should probably check that
out again using a remote server if we're going to switch the default;
alternatively, what about making it configurable, let the user find the one
that's best for them?

**Comment by brucek** [comment]
So I did some quick benchmarking and it looks like [Typhoeus is basically as fast or faster](https://gist.github.com/brucek/2f8e85bba9a59463f6d6ccc7f31d8831) (at least on a normal https:// web connection).

The configurable approach is probably ideal, but it might be a little bit before I can look at that, however.

**Comment by cheerfulstoic** [comment]
I'm all for Typhoeus if it's at least as fast.

As for configuration, I wonder is it possible to configure the adaptor via the `init_params` (passed in as the `:initialize` key to the last argument of `open` which I think is also configurable in the `railtie`)

**Comment by brucek** [comment]
Closing in favor of #273

**Pull request closed without merging**
